// deno-lint-ignore no-explicit-any
type todo = any;

// deno-lint-ignore no-namespace
namespace JSX {
  // deno-lint-ignore no-empty-interface
  interface Element extends HTMLElement {}

  interface IntrinsicElements {
    a: todo;
    abbr: todo;
    address: todo;
    area: todo;
    article: todo;
    aside: todo;
    audio: todo;
    b: todo;
    base: todo;
    bdi: todo;
    bdo: todo;
    big: todo;
    blockquote: todo;
    body: todo;
    br: todo;
    button: todo;
    canvas: todo;
    caption: todo;
    cite: todo;
    code: todo;
    col: todo;
    colgroup: todo;
    data: todo;
    datalist: todo;
    dd: todo;
    del: todo;
    details: todo;
    dfn: todo;
    dialog: todo;
    div: todo;
    dl: todo;
    dt: todo;
    em: todo;
    embed: todo;
    fieldset: todo;
    figcaption: todo;
    figure: todo;
    footer: todo;
    form: todo;
    h1: todo;
    h2: todo;
    h3: todo;
    h4: todo;
    h5: todo;
    h6: todo;
    head: todo;
    header: todo;
    hgroup: todo;
    hr: todo;
    html: todo;
    i: todo;
    iframe: todo;
    img: todo;
    input: todo;
    ins: todo;
    kbd: todo;
    keygen: todo;
    label: todo;
    legend: todo;
    li: todo;
    link: todo;
    main: todo;
    map: todo;
    mark: todo;
    menu: todo;
    menuitem: todo;
    meta: todo;
    meter: todo;
    nav: todo;
    noindex: todo;
    noscript: todo;
    object: todo;
    ol: todo;
    optgroup: todo;
    option: todo;
    output: todo;
    p: todo;
    param: todo;
    picture: todo;
    pre: todo;
    progress: todo;
    q: todo;
    rp: todo;
    rt: todo;
    ruby: todo;
    s: todo;
    samp: todo;
    script: todo;
    section: todo;
    select: todo;
    small: todo;
    source: todo;
    span: todo;
    strong: todo;
    style: todo;
    sub: todo;
    summary: todo;
    sup: todo;
    table: todo;
    tbody: todo;
    td: todo;
    textarea: todo;
    tfoot: todo;
    th: todo;
    thead: todo;
    time: todo;
    title: todo;
    tr: todo;
    track: todo;
    u: todo;
    ul: todo;
    var: todo;
    video: todo;
    wbr: todo;
  }
}

export type { JSX };
